using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class CartSyncModel
{
    [RealtimeProperty(1, true, true)] 
    private string _total = "Total: $0.00";
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class CartSyncModel : RealtimeModel {
    public string total {
        get {
            return _totalProperty.value;
        }
        set {
            if (_totalProperty.value == value) return;
            _totalProperty.value = value;
            InvalidateReliableLength();
            FireTotalDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(CartSyncModel model, T value);
    public event PropertyChangedHandler<string> totalDidChange;
    
    public enum PropertyID : uint {
        Total = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _totalProperty;
    
    #endregion
    
    public CartSyncModel() : base(null) {
        _totalProperty = new ReliableProperty<string>(1, _total);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _totalProperty.UnsubscribeCallback();
    }
    
    private void FireTotalDidChange(string value) {
        try {
            totalDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _totalProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _totalProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Total: {
                    changed = _totalProperty.Read(stream, context);
                    if (changed) FireTotalDidChange(total);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _total = total;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
